USE ROLE ACCOUNTADMIN;

DROP TABLE IF EXISTS AIRBNB.RAW.raw_listings;
DROP TABLE IF EXISTS AIRBNB.RAW.raw_reviews;
DROP TABLE IF EXISTS AIRBNB.RAW.raw_hosts;

DROP SCHEMA IF EXISTS AIRBNB.RAW;

DROP DATABASE IF EXISTS AIRBNB;

DROP USER IF EXISTS dbt;

REVOKE ALL ON WAREHOUSE COMPUTE_WH FROM ROLE TRANSFORM;
REVOKE ROLE TRANSFORM FROM ROLE ACCOUNTADMIN;
DROP ROLE IF EXISTS TRANSFORM;

DROP WAREHOUSE IF EXISTS COMPUTE_WH;