version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns:
      - name: listing_id
        description: Primary key for the listing
        tests:
          - unique
          - not_null
        
      - name: host_id
        description: The hosts's id. References the host table.
        tests:
          - relationships:
             arguments:
               to: ref('dim_hosts_cleansed')
               field: host_id
          - not_null

      - name: room_type
        description: Type of the apartment / room
        tests:
          - accepted_values:
             arguments:
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']

      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        tests:
          - positive_value

  - name: dim_hosts_cleansed
    columns:
      - name: host_id
        tests:
          - not_null
          - unique
      
      - name: host_name
        tests:
          - not_null
      
      - name: is_superhost
        tests:
          - not_null
          - accepted_values:
             arguments:
               values: ['t', 'f']
  
  - name: fct_reviews
    columns:
      - name: listing_id
        tests:
          - relationships:
             arguments:
               to: ref('dim_listings_cleansed')
               field: listing_id

      - name: reviewer_name
        tests:
          - not_null
      
      - name: review_sentiment
        tests:
          - accepted_values:
             arguments:
               values: ['positive', 'neutral', 'negative']

  - name: dim_hosts_cleansed
    config:
        contract:
          enforced: true
    columns:
      - name: host_id
        data_type: integer
      - name: host_name
        data_type: string
      - name: is_superhost
        data_type: string
      - name: updated_at
        data_type: timestamp
      - name: created_at
        data_type: timestamp